apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: CatalogSource
      name: okderators
      namespace: openshift-marketplace
    patch: |-
      - op: replace
        path: /spec/image
        value: quay.io/okderators/catalog-index:4.19
