apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: openshift-cert-manager-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable-v1
