apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

resources:
  - ../../base

patches:
  - target:
      kind: Namespace
      name: openshift-lvm-storage
    patch: |-
      - op: replace
        path: /metadata/name
        value: openshift-storage

  - target:
      kind: OperatorGroup
      name: openshift-storage-operatorgroup
      namespace: openshift-lvm-storage
    patch: |-
      - op: replace
        path: /spec/targetNamespaces
        value: openshift-storage

  - target:
      kind: Subscription
      name: lvms
      namespace: openshift-lvm-storage
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable-4.19
