apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: 3scale
    patch: |-
      - op: replace
        path: /spec/channel
        value: threescale-2.15
