apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: nfs-provisioner-operator
      namespace: nfsprovisioner-operator
    patch: |-
      - op: replace
        path: /spec/startingCSV
        value: nfs-provisioner-operator.v0.0.8
