apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: 3scale
  namespace: 3scale
spec:
  channel: PATCH-ME
  installPlanApproval: Automatic
  name: 3scale-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
