apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: devspaces
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable

  - target:
      kind: CheCluster
      name: devspaces
    patch: |-
      - op: replace
        path: /spec/devEnvironments/allowedSources/urls/0
        value: PATCH-ME
