apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - externalsecretsconfig.yaml

patches:
  - target:
      kind: Subscription
      name: openshift-external-secrets-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable-v1

  - target:
      kind: Subscription
      name: openshift-external-secrets-operator
    patch: |-
      - op: add
        path: /spec/startingCSV
        value: external-secrets-operator.v1.0.0
