apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: hco-operatorhub
    patch: |-
      - op: replace
        path: /spec/startingCSV
        value: kubevirt-hyperconverged-operator.v4.22.0
