apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: lvms
      namespace: openshift-lvm-storage
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable-4.21
